### ISSUE TITLE
未在根目录下找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

### ISSUE THREAD

**Issue by hankinghu** [swy1996/scf_imgbed#5]
上传后提示：未在根目录下找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by swy1996** [comment]
查询下执行方法是否为index.main_handler，下载的zip包是否有嵌套文件夹。
